#
# The Kubernetes deployment file for our Web Host
#

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhost
  labels:
    app: webhost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhost
  template:
    metadata:
      labels:
        app: webhost
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: webhost
        image: webhost:v1
        imagePullPolicy: Never
        volumeMounts:
          - name: webhost-config
            mountPath: /usr/webhost/host.config.json
            subPath: host.config.json
            readOnly: true
          - name: spa-config
            mountPath: /usr/webhost/spa.config.json
            subPath: spa.config.json
            readOnly: true
          - name: ssl-cert
            mountPath: /usr/webhost/certs
            readOnly: true
      volumes:
        - name: webhost-config
          configMap:
            name: webhost-config
        - name: spa-config
          configMap:
            name: spa-config
        - name: ssl-cert
          secret:
            secretName: webhost-pkcs12-password
---
kind: Service
apiVersion: v1
metadata:
  name: webhost-svc
spec:
  selector:
    app: webhost
  ports:
  - protocol: "TCP"
    port: 8102
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhost-cert
spec:
  secretName: webhost-pkcs12-password
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: webhost-svc.default.svc
  dnsNames:
  - webhost-svc
  - webhost-svc.default.svc
  - webhost-svc.default.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: webhost-pkcs12-password
        key: password