#
# Configure based on the results of this command:
# docker network inspect kind -f '{{.IPAM.Config}}'
#
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.29.255.200-172.29.255.250