#
# The Kubernetes resources for our Web Host, which runs on port 8101
#
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: webhost-cert
spec:
  secretName: webhost-pkcs12-password
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: webhost-svc.default.svc
  dnsNames:
  - webhost-svc
  - webhost-svc.default.svc
  - webhost-svc.default.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: webhost-pkcs12-password
        key: password
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhost
  labels:
    app: webhost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhost
  template:
    metadata:
      labels:
        app: webhost
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: webhost
        image: webhost:v1
        imagePullPolicy: Never
        volumeMounts:
          - name: webhost-config
            mountPath: /usr/webhost/host.config.json
            subPath: host.config.json
            readOnly: true
          - name: spa-config
            mountPath: /usr/webhost/spa.config.json
            subPath: spa.config.json
            readOnly: true
          - name: ssl-cert
            mountPath: /usr/webhost/certs
            readOnly: true
      volumes:
        - name: webhost-config
          configMap:
            name: webhost-config
        - name: spa-config
          configMap:
            name: spa-config
        - name: ssl-cert
          secret:
            secretName: webhost-pkcs12-password
---
kind: Service
apiVersion: v1
metadata:
  name: webhost-svc
spec:
  selector:
    app: webhost
  ports:
  - protocol: "TCP"
    port: 8101
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webhost-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/secure-backends: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
spec:
  tls:
    - hosts:
        - web.mycluster.com
      secretName: mycluster-com-tls
  rules:
    - host: web.mycluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhost-svc
                port:
                  number: 8101