_format_version: '2.1'
_transform: true
services:

# The SPA calls https://api.mycompany.com/tokenhandler to perform OAuth requests
- name: tokenhandler
  url: https://tokenhandler-svc:8101/tokenhandler
  routes:
  - name: tokenhandler-api-route
    paths:
    - /tokenhandler

  # The SPA calls https://api.mycompany.com/api to access business data
- name: finalapi
  url: https://finalapi-svc:8101/api
  routes:
  - name: finalapi-route
    paths:
    - /api
  plugins:
  - name: oauth-proxy
    config:
      encryption_key: aPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq
      cookie_name_prefix: mycompany
      trusted_web_origins:
      - https://web.mycompany.com
