#
# The Kubernetes resources for the core Elasticsearch service
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          env:
            - name: discovery.type
              value: 'single-node'
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.authc.api_key.enabled
              value: 'false'
            - name: ELASTIC_PASSWORD
              value: 'Password1'
---
kind: Service
apiVersion: v1
metadata:
  name: elastic-svc
spec:
  selector:
    app: elastic
  ports:
    - protocol: "TCP"
      port: 9200
