#
# Cluster base configuration
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: oauth
nodes:
  - role: control-plane
  - role: worker
  - role: worker
---
kind: Namespace
apiVersion: v1
metadata:
  name: deployed