#
# Deploy a utilities POD for troubleshooting
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsutils
  namespace: deployed
spec:
  selector:
    matchLabels:
      app: dnsutils
  replicas: 1
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
      - name: dnsutils
        image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent